#pragma once

//from glfw3.h

#define FJORD_MOUSE_BUTTON_1         0
#define FJORD_MOUSE_BUTTON_2         1
#define FJORD_MOUSE_BUTTON_3         2
#define FJORD_MOUSE_BUTTON_4         3
#define FJORD_MOUSE_BUTTON_5         4
#define FJORD_MOUSE_BUTTON_6         5
#define FJORD_MOUSE_BUTTON_7         6
#define FJORD_MOUSE_BUTTON_8         7
#define FJORD_MOUSE_BUTTON_LAST      FJORD_MOUSE_BUTTON_8
#define FJORD_MOUSE_BUTTON_LEFT      FJORD_MOUSE_BUTTON_1
#define FJORD_MOUSE_BUTTON_RIGHT     FJORD_MOUSE_BUTTON_2
#define FJORD_MOUSE_BUTTON_MIDDLE    FJORD_MOUSE_BUTTON_3